// <auto-generated />
using System;
using System.Collections.Generic;
using HealthJournal.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthJournal.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthJournal.Api.Domain.Journal.JournalEntryBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("JournalWeekId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("JournalWeekId")
                        .HasDatabaseName("IX_JournalEntries_JournalWeekId");

                    b.ToTable("JournalEntries", (string)null);

                    b.HasDiscriminator<string>("EntryType").HasValue("Base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HealthJournal.Api.Domain.Journal.JournalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("JournalUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c23bc95-9c5f-4ff6-888c-3b2eccf766f2"),
                            CreatedAt = new DateTime(2026, 9, 9, 12, 10, 10, 0, DateTimeKind.Utc),
                            ExtUserId = "dummy-user"
                        });
                });

            modelBuilder.Entity("HealthJournal.Api.Domain.Journal.JournalWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("End")
                        .HasColumnType("date");

                    b.Property<Guid>("JournalUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("date");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "WeekOfYear", "HealthJournal.Api.Domain.Journal.JournalWeek.WeekOfYear#WeekOfYear", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Week")
                                .HasColumnType("integer");

                            b1.Property<int>("Year")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.HasIndex("JournalUserId", "Start")
                        .HasDatabaseName("IX_JournalWeeks_JournalUserId_WeekOfYear");

                    b.ToTable("JournalWeeks", (string)null);
                });

            modelBuilder.Entity("HealthJournal.Api.Domain.Journal.ActivityEntry", b =>
                {
                    b.HasBaseType("HealthJournal.Api.Domain.Journal.JournalEntryBase");

                    b.Property<DateOnly>("PerformedAt")
                        .HasColumnType("date");

                    b.HasDiscriminator().HasValue("Activity");
                });

            modelBuilder.Entity("HealthJournal.Api.Domain.Journal.JournalEntryBase", b =>
                {
                    b.HasOne("HealthJournal.Api.Domain.Journal.JournalWeek", "JournalWeek")
                        .WithMany("Entries")
                        .HasForeignKey("JournalWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalWeek");
                });

            modelBuilder.Entity("HealthJournal.Api.Domain.Journal.JournalWeek", b =>
                {
                    b.HasOne("HealthJournal.Api.Domain.Journal.JournalUser", "JournalUser")
                        .WithMany("JournalWeeks")
                        .HasForeignKey("JournalUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalUser");
                });

            modelBuilder.Entity("HealthJournal.Api.Domain.Journal.JournalUser", b =>
                {
                    b.Navigation("JournalWeeks");
                });

            modelBuilder.Entity("HealthJournal.Api.Domain.Journal.JournalWeek", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
